connection: &connection
  adapter: postgresql
  encoding: unicode
  host:     localhost
  pool: 5
  username: mateusz 
  password: password

development:
  <<: *connection
  database: er_development

test: &test
  <<: *connection
  database: er_test